name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.13.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: Memento

      - name: Run tests
        run: npm test
        working-directory: Memento

      - name: Lint code
        run: npm run lint
        working-directory: Memento

      - name: Build project
        run: npm run build
        working-directory: Memento
